<?php
$apikey="rzp_test_MWQ18j5O2Zj2x5";
session_start();
$name=$_SESSION['name'];
?>
<form action="confirm.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount=<?php echo 5*100; ?> // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Centralized Ehospitalization System"
    data-description="Safe pay for medicines"
    data-image="3.jpg"
    data-prefill.name=<?php echo $name ?>;
    data-prefill.email="jamwal.com"
    data-theme.color="#0000ff"
>
</script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
<script>
        document.addEventListener("DOMContentLoaded", function(event) {
            document.querySelector(".razorpay-payment-button").click();
        });
    </script>
</form>
